apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: main
          image: minio/minio
          env:
            - name: MINIO_ACCESS_KEY
              value: admin
            #  valueFrom:
            #    secretKeyRef:
            #      name: my-minio-cred
            #      key: accessKey
            - name: MINIO_SECRET_KEY
              value: password
            #  valueFrom:
            #    secretKeyRef:
            #      name: my-minio-cred
            #      key: secretKey
          ports:
            - containerPort: 9000
            - containerPort: 9001
          command: [minio]
          args:
          - server 
          - --console-address
          - :9001
          - /data 
          lifecycle:
            postStart:
              exec:
                command: [mkdir, -p, /data/default]
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
