- name: emissary
  selector:
    matchLabels:
      workflows.argoproj.io/container-runtime-executor: emissary
- name: pns
  selector:
    matchLabels:
      workflows.argoproj.io/container-runtime-executor: pns
- name: k8sapi
  selector:
    matchLabels:
      workflows.argoproj.io/container-runtime-executor: k8sapi