apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    workflows.argoproj.io/default-artifact-repository: artifactRepository
  name: artifact-repositories
data:
  artifactRepository: |
    s3:
      bucket: default
      endpoint: minio.minio.svc.cluster.local:9000    
      insecure: true                 
      accessKeySecret:              
        name: my-minio-cred
        key: accessKey
      secretKeySecret:                
        name: my-minio-cred
        key: secretKey       