apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresult
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow
subjects:
- kind: ServiceAccount
  name: workflow
